# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- production
steps:
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    SourceFolder: Production/Azure/Scripts-ReleasePipelineClassic
    Contents: |
      **/*.ps1
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)/wacs'
  inputs:
    SourceFolder: Production/win-acme
    Contents: |
      **/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)/win-acme'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    